# Numpy Tutorial

In [1]:
# install numpy
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip


In [2]:
# import the library
import numpy as np

# The basics of NumPy Arrays

In [3]:
# 1D array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
# 2D array
b = np.array([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]])
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [5]:
# Get dimensions
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [8]:
# Get type
mat = [[1,2,3],[4,5,6],[7,8,9]]
c = np.array(mat)
print(c.dtype)

c = np.array(mat, dtype='int16')
print(c.dtype)

int64
int16


In [9]:
# Get size of array and itemsize
print(f"{c.itemsize} bytes")
print(f"{b.itemsize} bytes")

print(f"{c.size} elements")
print(f"{a.size} elements")

# space utilized
print(b.nbytes)

2 bytes
8 bytes
9 elements
3 elements
64


# Accessing, Changing specific elements, rows, and columns ...

In [10]:
# initialize a numpy 2D array
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get specific elements with [r, c]
print(a[1, 4])
print(a[1, -3])
print(a[1][4])

12
12
12


In [12]:
# Get a specific row
print(a[1, :])
print(a[1])

[ 8  9 10 11 12 13 14]
[ 8  9 10 11 12 13 14]


In [13]:
# Get a specific column
a[:, 4]

array([ 5, 12])

In [14]:
# Get a little more fancy [startindex:endindex:stepsize]
print(a)
a[0, 1:6:2]


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

In [15]:
# Modify array
a[0, 3] = 20
a[:, 2] = 15
a[:, -1] = [10, 10]
a


array([[ 1,  2, 15, 20,  5,  6, 10],
       [ 8,  9, 15, 11, 12, 13, 10]])

# 3D examples

In [16]:
a = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(a.shape)
a

(2, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
# access elements (work outside in)
print(a[1, 0, 1])

8


In [18]:
print(a[0, 1, :])
print(a[:, :, -1])

[4 5 6]
[[ 3  6]
 [ 9 12]]


In [19]:
# modify
a[:, :, -2] = np.array([[10, 10], [10, 10]])
a

array([[[ 1, 10,  3],
        [ 4, 10,  6]],

       [[ 7, 10,  9],
        [10, 10, 12]]])

# Initializing different types of arrays

In [20]:
# All 0's matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4), dtype='int16')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [22]:
# all 1's matrix
np.ones((4,3,3), dtype='int16')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [23]:
# Any other number
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
# Same dimension as some other array
np.full_like(a, 99)

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [25]:
# Random decimal numers
np.random.rand(4, 2)


array([[0.94940513, 0.83228727],
       [0.50364882, 0.05541086],
       [0.31343402, 0.15708517],
       [0.60981667, 0.47735823]])

In [26]:
print(np.random.random_sample(a.shape))
print(np.random.randint(-2, 7, size=a.shape))

[[[0.89516997 0.5873676  0.71748512]
  [0.6571365  0.47661255 0.37558456]]

 [[0.88630166 0.44888855 0.74593956]
  [0.96499355 0.15194297 0.66396317]]]
[[[5 6 0]
  [2 3 6]]

 [[3 2 2]
  [6 6 0]]]


In [27]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Repeate array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [29]:
r1 = np.repeat(arr, 3, axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [30]:
# Build an array using functions
arr = np.zeros((5,5), dtype='int16')
arr[:, 0] = 1 # first col as 1
arr[:, -1] = 1  # last columns as 1
arr[0, :] = 1
arr[-1, :] = 1
arr[2, 2] = 9 # mid element
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [31]:
output = np.ones((5,5))
output

z = np.zeros((3,3))
z[1,1] = 9
output[1:-1, 1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# Copy array
d = a.copy()
d

array([[[ 1, 10,  3],
        [ 4, 10,  6]],

       [[ 7, 10,  9],
        [10, 10, 12]]])

# Mathematics operations

In [33]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [34]:
# element-wise operations
print(a+2)
print(a*2)
print(a**2)

[3 4 5 6]
[2 4 6 8]
[ 1  4  9 16]


In [35]:
b = np.array([3,4,5,6])
a+b

array([ 4,  6,  8, 10])

In [36]:
print(np.cos(a))
print(np.sin(a))
print(np.log(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


# Linear Algebra (Matrix Operations)

In [37]:
a = np.ones((2,3))
b = np.full((3,2), 4)

print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


In [38]:
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

In [39]:
# Find determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

There is a lot of thing you can do with matrices and Linear Algerbra in numpy

> Determinant
> Trace
> Singular Vector decomposition
> Eigenvalues
> Matrix norm
> Inverse
etc..

# Statistics

In [40]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
print(np.min(stats))
print(np.max(stats))
print(np.max(stats, axis=0))
print(np.sum(stats, axis=0))


1
6
[4 5 6]
[5 7 9]


# Reorganizing arrays

In [42]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

after = after.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4 5 6 7 8]]


In [43]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([3,4,5,6])

np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [44]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.full((2,2), 10)

np.hstack([h1, h2, h2])

array([[ 1.,  1.,  1.,  1., 10., 10., 10., 10.],
       [ 1.,  1.,  1.,  1., 10., 10., 10., 10.]])

# Miscellaneous

Load data from file

In [45]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)

filedata = filedata.astype('int32') # convert to another data type
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean masking and Advanced indexing

In [46]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [47]:
filedata[filedata > 50] # this works because see below

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [48]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,2,7]]

array([1, 3, 8])

In [49]:
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [50]:
np.all(filedata > 50, axis = 0) # check if any  >50 col wise

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [51]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [52]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

# Quiz time

In [53]:
mat = np.array(list(range(1,31)))
print(mat)

mat = mat.reshape((6,5))
mat

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
# indexing 
mat[2:-1, :2]

array([[11, 12],
       [16, 17],
       [21, 22]])

In [55]:
mat[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [56]:
mat[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])